#ifndef __LANGUAGE_H
#define __LANGUAGE_H
#endif

#define EnregTemp    	"Temporary Saving"
#define EnregDef     	"Permanent Saving"

#define ErrRead			"Database Reading Error:"
#define ErrOpen			"File Opening Error:    "
#define ErrUpDate    	"Database update Error"
#define ErrDelete			"Select a curve before pressing 'F6' !..."
#define ErrSame      	"2 Products have the same type number"
#define DelOne				"Delete one of the two selected"
#define ErrSave			"File saving error"
#define ErrDelay			"Error in recording the delays"
#define UnvalidDelay    "The delay is unvalid ...!"
#define ErrRecord       "Error in recording the delays"
#define TooDelays			"Too many delays !"
#define ErrDelaysDel    "No delay can be deleted"
#define DelayNotDefined "This delay was not defined in the list"
#define ErrLoadingDelay "No delay can be loaded"
#define NoDelayProgr		"No delay has been programmed ...!"
#define ErrNbCurve		"Error in recording curves displayed"
#define TooCurves       "You can select only 6 curves"

#define Title1				"Furnace Configuration modified"
#define Title2				"Model Configuration modified"
#define Title3				"Products Configuration modified"
#define Title4				"Heat Curves Configuration modified"
#define WarningTitle   	"Warning"
#define OverWriteQst		"Overwrite the loaded delay?"

#define PaceTitle			"PACING MODE"
#define Theoretical     "Theoretical"
#define Measured			"Measured"
#define PaceModifTitle  "Pacing mode modified"
#define ConfirmQst		"Save the new pacing mode?"
